services:
  postgres:
    image: postgres:16-alpine
    container_name: meeting_mgmt_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: meeting_mgmt
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mailpit:
    image: axllent/mailpit:latest
    container_name: meeting_mgmt_mailpit
    restart: always
    ports:
      - "1025:1025" # SMTP port
      - "8025:8025" # Web UI
volumes:
  postgres_data:
