export const ERROR_CODES = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  ROOM_NOT_FOUND: 'ROOM_NOT_FOUND',
  MEETING_NOT_FOUND: 'MEETING_NOT_FOUND',
  CONFLICT: 'CONFLICT',
  CONFLICT_ROOM: 'CONFLICT_ROOM',
  CONFLICT_PARTICIPANT: 'CONFLICT_PARTICIPANT',
  SCHEDULE_CONFLICT: 'SCHEDULE_CONFLICT',
  INVALID_STATE: 'INVALID_STATE',
  PAYLOAD_TOO_LARGE: 'PAYLOAD_TOO_LARGE',
  UNSUPPORTED_MEDIA_TYPE: 'UNSUPPORTED_MEDIA_TYPE',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];

export const WARNING_CODES = {
  INVITATION_EMAIL_FAILED: 'INVITATION_EMAIL_FAILED',
  SCHEDULE_CONFLICT_OVERRIDDEN: 'SCHEDULE_CONFLICT_OVERRIDDEN',
} as const;

export type WarningCode = (typeof WARNING_CODES)[keyof typeof WARNING_CODES];
